version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: my-thc-app-posgress
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: '10102025!'
      POSTGRES_DB: 'take_home_challenge'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-db-network
    healthcheck:
      test: []
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: 
networks:
  postgres-db-network:
      driver: bridge
