version: 2.1

orbs:
  coveralls: coveralls/coveralls@2.2.5

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Check Python Version
          command: python --version
      - run:
          name: Install virtual env
          command: python3 -m venv .venv
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Integration Test
          command: pytest
      - run:
          name: Run Tests with Coverage
          command: coverage run -m pytest tests/
          
      - run:
          name: View Terminal Report
          command: coverage report -m
          
      - run:
          name: Generate XML for Coveralls 
          command: coverage xml

      - coveralls/upload:
          coverage_file: ./coverage.xml
          coverage_format: cobertura  # Explicitly tells the orb to read Python's XML data

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
