version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Check Python Version
          command: python --version
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install virtual env
          command: python3 -m venv .venv
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Integration Test
          command: pytest

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
