"""add phone column

Revision ID: 303232495eb3
Revises: 546d22243b8b
Create Date: 2026-08-18 15:07:03.194055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303232495eb3'
down_revision: Union[str, Sequence[str], None] = '546d22243b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_and_pokemons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_and_pokemons', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
