"""add mobile column

Revision ID: 546d22243b8b
Revises: 652ecf41eff3
Create Date: 2026-08-18 14:35:01.571815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546d22243b8b'
down_revision: Union[str, Sequence[str], None] = '652ecf41eff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_and_pokemons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_and_pokemons', schema=None) as batch_op:
        batch_op.drop_column('mobile')

    # ### end Alembic commands ###
