"""add address column

Revision ID: 652ecf41eff3
Revises: 03c178fc2070
Create Date: 2026-08-18 14:33:41.925355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652ecf41eff3'
down_revision: Union[str, Sequence[str], None] = '03c178fc2070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_and_pokemons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_and_pokemons', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
